# This is a basic workflow to help you get started with Actions

name: Deploy Mobile Controller Website

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: mobileAppWebsite/polar-plotter-mobile-controller/**

      - name: Setup Node.JS
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v4

      - name: Install Dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm ci
        working-directory: ./mobileAppWebsite/polar-plotter-mobile-controller/

      - name: Build Package
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run build
        working-directory: ./mobileAppWebsite/polar-plotter-mobile-controller/

      - name: Deploy to S3
        uses: reggionick/s3-deploy@v4
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          bucket-region: ${{ secrets.AWS_S3_BUCKET_REGION }}
          dist-id: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /index.html
          folder: 'mobileAppWebsite/polar-plotter-mobile-controller/dist'
          delete-removed: true
